theme: minima
title: My Cyber Path
author: adrophix
description: "This is supposed to be just a 'blog' (read:diary) to document everything I am learning in this field, and the progress I am making with my skills. Things like efforts to obtain a certification, notes about what I am working on, and topics that may interest me."
